# Clock
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

# Switches
 set_property PACKAGE_PIN V17 [get_ports {StartPause}]
    set_property IOSTANDARD LVCMOS33 [get_ports {StartPause}]
 set_property PACKAGE_PIN V16 [get_ports {Mute}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Mute}]
 set_property PACKAGE_PIN W16 [get_ports {Repeat}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Repeat}]
 set_property PACKAGE_PIN W17 [get_ports {Music}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Music}]
# set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
# set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
# set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
# set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
# set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
# set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
# set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
# set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
# set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
# set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
# set_property PACKAGE_PIN T1 [get_ports {sw[14]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
# set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]

# LEDs
 set_property PACKAGE_PIN U16 [get_ports {Volume[0]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {Volume[0]}]
 set_property PACKAGE_PIN E19 [get_ports {Volume[1]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {Volume[1]}]
 set_property PACKAGE_PIN U19 [get_ports {Volume[2]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {Volume[2]}]
 set_property PACKAGE_PIN V19 [get_ports {Volume[3]}]
     set_property IOSTANDARD LVCMOS33 [get_ports {Volume[3]}]

# 7 segment display
 set_property PACKAGE_PIN W7 [get_ports {DISPLAY[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[0]}]
 set_property PACKAGE_PIN W6 [get_ports {DISPLAY[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[1]}]
 set_property PACKAGE_PIN U8 [get_ports {DISPLAY[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[2]}]
 set_property PACKAGE_PIN V8 [get_ports {DISPLAY[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[3]}]
 set_property PACKAGE_PIN U5 [get_ports {DISPLAY[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[4]}]
 set_property PACKAGE_PIN V5 [get_ports {DISPLAY[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[5]}]
 set_property PACKAGE_PIN U7 [get_ports {DISPLAY[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[6]}]
    
     set_property PACKAGE_PIN U2 [get_ports {DIGIT[0]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[0]}]
     set_property PACKAGE_PIN U4 [get_ports {DIGIT[1]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[1]}]
     set_property PACKAGE_PIN V4 [get_ports {DIGIT[2]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[2]}]
     set_property PACKAGE_PIN W4 [get_ports {DIGIT[3]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {DIGIT[3]}]


# Buttons
 set_property PACKAGE_PIN U18 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]
 set_property PACKAGE_PIN T18 [get_ports VolumeUp]
    set_property IOSTANDARD LVCMOS33 [get_ports VolumeUp]
# set_property PACKAGE_PIN W19 [get_ports btnL]
#    set_property IOSTANDARD LVCMOS33 [get_ports btnL]
# set_property PACKAGE_PIN T17 [get_ports btnR]
#    set_property IOSTANDARD LVCMOS33 [get_ports btnR]
 set_property PACKAGE_PIN U17 [get_ports VolumeDown]
    set_property IOSTANDARD LVCMOS33 [get_ports VolumeDown]

# Pmod I2S 
set_property PACKAGE_PIN A14 [get_ports {audio_mclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_mclk}]
set_property PACKAGE_PIN A16 [get_ports {audio_lrck}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_lrck}]
set_property PACKAGE_PIN B15 [get_ports {audio_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_sck}]
set_property PACKAGE_PIN B16 [get_ports {audio_sdin}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_sdin}]